// DTCG token tree -> Tailwind v4 `@theme { ... }` CSS string.
//
// This is the deterministic, offline half of the token pipeline: given a W3C
// DTCG tokens object (the committed `tokens/tokens.json`), it emits the exact
// `src/theme.css` artifact. Because it needs no network, CI can run it to guard
// against drift between `tokens.json` and the committed `theme.css`.
//
// Namespace mapping rules (see token-pipeline ADR 2026-05-27):
//   color.*                -> --color-<path>
//   font.family.<x>        -> --font-<x>           (Tailwind family namespace, NOT --font-family-*)
//   font.weight.<x>        -> --font-weight-<x>
//   text.* (typography)    -> --text-<path> + --text-<path>--{font-family,font-weight,line-height,letter-spacing}
//   shadow.*               -> --shadow-<path> (flattened box-shadow syntax, comma-joined for composites)

const DEFAULT_HEADER = [
  "/* Generated by build-tokens.mjs. Do not edit by hand. */",
  "/* Source: Figma file UI-Exercise (key i4WmV5Gfk9uivVQXC5NY8j) */",
];

const dtcgPathToCssVar = (parts) => {
  if (parts[0] === "font" && parts[1] === "family") return "--font-" + parts.slice(2).join("-");
  if (parts[0] === "font" && parts[1] === "weight")
    return "--font-weight-" + parts.slice(2).join("-");
  return "--" + parts.join("-");
};

const resolveRef = (str) => {
  const m = String(str).match(/^\{([\w.-]+)\}$/);
  return m ? `var(${dtcgPathToCssVar(m[1].split("."))})` : str;
};

/**
 * @param {object} dtcg  parsed DTCG token tree ({ color, font, text, shadow })
 * @param {object} [opts]
 * @param {string[]} [opts.header]  leading comment lines (default: the canonical header)
 * @returns {string} the full theme.css contents (trailing newline included)
 */
export function dtcgToCss(dtcg, opts = {}) {
  const header = opts.header ?? DEFAULT_HEADER;
  const css = [...header, "", "@theme {"];

  const emitColor = (obj, prefix) => {
    for (const [k, v] of Object.entries(obj)) {
      if (k.startsWith("$")) continue;
      if (v?.$type === "color") css.push(`  --color-${[...prefix, k].join("-")}: ${v.$value};`);
      else if (v && typeof v === "object") emitColor(v, [...prefix, k]);
    }
  };
  emitColor(dtcg.color ?? {}, []);
  css.push("");

  for (const [k, v] of Object.entries(dtcg.font?.family ?? {})) {
    if (k.startsWith("$")) continue;
    css.push(`  --font-${k}: ${v.$value.map((s) => `"${s}"`).join(", ")};`);
  }
  css.push("");

  for (const [k, v] of Object.entries(dtcg.font?.weight ?? {})) {
    if (k.startsWith("$")) continue;
    css.push(`  --font-weight-${k}: ${v.$value};`);
  }
  css.push("");

  const emitText = (obj, prefix) => {
    for (const [k, v] of Object.entries(obj)) {
      if (k.startsWith("$")) continue;
      if (v?.$type === "typography") {
        const n = [...prefix, k].join("-");
        const val = v.$value;
        css.push(`  --text-${n}: ${val.fontSize};`);
        css.push(`  --text-${n}--font-family: ${resolveRef(val.fontFamily)};`);
        css.push(`  --text-${n}--font-weight: ${resolveRef(val.fontWeight)};`);
        css.push(`  --text-${n}--line-height: ${val.lineHeight};`);
        if (val.letterSpacing && val.letterSpacing !== "normal") {
          css.push(`  --text-${n}--letter-spacing: ${val.letterSpacing};`);
        }
        css.push("");
      } else if (v && typeof v === "object") {
        emitText(v, [...prefix, k]);
      }
    }
  };
  emitText(dtcg.text ?? {}, []);

  const emitShadow = (obj, prefix) => {
    for (const [k, v] of Object.entries(obj)) {
      if (k.startsWith("$")) continue;
      if (v?.$type === "shadow") {
        const sh = Array.isArray(v.$value) ? v.$value : [v.$value];
        css.push(
          `  --shadow-${[...prefix, k].join("-")}: ${sh
            .map(
              (s) =>
                `${s.inset ? "inset " : ""}${s.offsetX} ${s.offsetY} ${s.blur} ${s.spread} ${s.color}`,
            )
            .join(", ")};`,
        );
      } else if (v && typeof v === "object") {
        emitShadow(v, [...prefix, k]);
      }
    }
  };
  emitShadow(dtcg.shadow ?? {}, []);

  css.push("}");
  return css.join("\n") + "\n";
}

export { dtcgPathToCssVar, resolveRef, DEFAULT_HEADER };
